ForumGFL/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ForumGFL.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace ForumGFL.Controllers
{
    public class AuthController : Controller
    {

        private SignInManager<IdentityUser> _signInManager;
        private UserManager<IdentityUser> _userManager;
        public AuthController(SignInManager<IdentityUser> signInManager, UserManager<IdentityUser> userManager)
        {
            _signInManager = signInManager;
            _userManager = userManager;
        }

        [HttpGet]
        public IActionResult Login()
        {
            //display page
            return View(new LoginViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel vm)
        {
            var result = await _signInManager.PasswordSignInAsync(vm.UserName, vm.Password, false, false);

            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public IActionResult Register()
        {
            //display page
            return View(new RegisterViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                return View(vm);
            }

            var newUser = new IdentityUser
            {
                UserName = vm.Username,
                Email = vm.Email,
            };
            var result = await _userManager.CreateAsync(newUser, vm.Password);

            if (result.Succeeded)
            {
                await _signInManager.SignInAsync(newUser, false);
                return RedirectToAction("Index", "Home");
            }

            return View(vm);
        }

    }
}

ForumGFL/Controllers/TopicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ForumGFL.Data.RepositoryOfMessages;
using ForumGFL.Data.RepositoryOfTopics;
using ForumGFL.Models;
using ForumGFL.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace ForumGFL.Controllers
{
    public class TopicController : Controller
    {

        private readonly IRepositoryOfTopics _topicRepo;
        private readonly IRepositoryOfMessages _msgRepo;
        private readonly UserManager<IdentityUser> _userManager;

        public TopicController(IRepositoryOfTopics topicRepo, IRepositoryOfMessages msgRepo, UserManager<IdentityUser> userManager)
        {
            _topicRepo = topicRepo;
            _msgRepo = msgRepo;
            _userManager = userManager;
    }

        public IActionResult ShowTopic(int id)
        {
            var topic = _topicRepo.GetTopic(id);
            List<ForumMessage> msgs = _msgRepo.GetMessages(id);
            TopicAndMsgsViewModel tmvm = new TopicAndMsgsViewModel();
            tmvm.Topic = topic;
            tmvm.Messages = msgs;
            tmvm.context = HttpContext;
            return View(tmvm);
        }

        public async Task<IActionResult> RemoveTopic(int id)
        {
            _topicRepo.RemoveTopic(id);
            await _topicRepo.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public async Task<IActionResult> CreateTopic(Topic topic)
        {
            topic.Author = HttpContext.User.Identity.Name;
            _topicRepo.AddTopic(topic);
            if (await _topicRepo.SaveChangesAsync())
                return RedirectToAction("Index", "Home");
            else return View(new TopicAndMsgsViewModel());
        }
        [HttpGet]
        public IActionResult CreateTopic()
        {
            return View(new TopicAndMsgsViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> CreateMessage(ForumMessage message, int id)
        {
            message.TopicId = id;
            message.Author = HttpContext.User.Identity.Name;
            _msgRepo.AddMessage(message);
            if (await _msgRepo.SaveChangesAsync())
                return RedirectToAction("ShowTopic", new { ID = id }) ;
            else return View(new TopicAndMsgsViewModel());
        }

        [HttpGet]
        public IActionResult CreateMessage(int id)
        {
            return View(new TopicAndMsgsViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> EditMessage(ForumMessage message, int id)
        {
            message.Id = id;
            message.LastUpdated = DateTime.Now;
            _msgRepo.UpdateMessage(message);
            if (await _msgRepo.SaveChangesAsync())
                return RedirectToAction("EditMessage", new { ID = id });
            else return View(new TopicAndMsgsViewModel());
        }

        [HttpGet]
        public IActionResult EditMessage(int id)
        {
            var msg = _msgRepo.GetMessage(id);
            TopicAndMsgsViewModel tmvm = new TopicAndMsgsViewModel();
            tmvm.Message = msg;
            return View(tmvm);
        }

    }
}

ForumGFL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ForumGFL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ForumGFL</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
                @if (User.Identity.IsAuthenticated)
                {
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Topic" asp-action="CreateTopic">Create Topic</a>
                            </li>
                        </ul>
                    </div>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Logout">Logout</a>
                            </li>
                        </ul>
                    </div>
                }
                else
                { 
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login">Sign In</a>
                            </li>
                        </ul>
                    </div>
                }
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        @*<div class="container">
            &copy; 2020 - ForumGFL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>*@
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>